[2024-06-11T21:45:13.707+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:45:13.759+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701276 manual__2024-06-11T21:41:03.459046+00:00 [queued]>
[2024-06-11T21:45:13.773+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701276 manual__2024-06-11T21:41:03.459046+00:00 [queued]>
[2024-06-11T21:45:13.774+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:45:13.796+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_701276> on 2024-06-11 21:41:03.459046+00:00
[2024-06-11T21:45:13.807+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_701276', 'manual__2024-06-11T21:41:03.459046+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmpqll1kev5']
[2024-06-11T21:45:13.811+0000] {standard_task_runner.py:91} INFO - Job 269: Subtask load_index_id_701276
[2024-06-11T21:45:13.811+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=202) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:45:13.813+0000] {standard_task_runner.py:63} INFO - Started process 203 to run task
[2024-06-11T21:45:13.896+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_701276 manual__2024-06-11T21:41:03.459046+00:00 [running]> on host f7fd8afd804e
[2024-06-11T21:45:14.054+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_701276' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T21:41:03.459046+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T21:41:03.459046+00:00'
[2024-06-11T21:45:14.056+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:45:14.132+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:45:14.134+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:45:14.135+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:45:14.149+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_701276, execution_date=20240611T214103, start_date=20240611T214513, end_date=20240611T214514
[2024-06-11T21:45:14.167+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 269 for task load_index_id_701276 (Task failed due to SystemExit(1); 203)
[2024-06-11T21:45:14.191+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:45:14.225+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:45:14.231+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
