[2024-04-27T23:23:18.336+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T23:23:18.564+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701228 manual__2024-04-27T22:35:33.025533+00:00 [queued]>
[2024-04-27T23:23:18.590+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701228 manual__2024-04-27T22:35:33.025533+00:00 [queued]>
[2024-04-27T23:23:18.591+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-27T23:23:18.622+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_701228> on 2024-04-27 22:35:33.025533+00:00
[2024-04-27T23:23:18.632+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_701228', 'manual__2024-04-27T22:35:33.025533+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmpc2wpkkjr']
[2024-04-27T23:23:18.637+0000] {standard_task_runner.py:91} INFO - Job 244: Subtask load_index_id_701228
[2024-04-27T23:23:18.645+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6263) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-27T23:23:18.648+0000] {standard_task_runner.py:63} INFO - Started process 6264 to run task
[2024-04-27T23:23:18.728+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_701228 manual__2024-04-27T22:35:33.025533+00:00 [running]> on host d933ead87eb5
[2024-04-27T23:23:18.934+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_701228' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T22:35:33.025533+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T22:35:33.025533+00:00'
[2024-04-27T23:23:18.937+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T23:23:59.519+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-04-27T23:23:59.521+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T23:23:59.523+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-04-27T23:23:59.547+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_701228, execution_date=20240427T223533, start_date=20240427T232318, end_date=20240427T232359
[2024-04-27T23:23:59.588+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 244 for task load_index_id_701228 (Task failed due to SystemExit(1); 6264)
[2024-04-27T23:23:59.641+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T23:23:59.690+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T23:23:59.701+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
