[2024-04-28T01:01:29.021+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T01:01:29.073+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_702022 manual__2024-04-27T22:35:33.025533+00:00 [queued]>
[2024-04-28T01:01:29.085+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_702022 manual__2024-04-27T22:35:33.025533+00:00 [queued]>
[2024-04-28T01:01:29.087+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T01:01:29.109+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_702022> on 2024-04-27 22:35:33.025533+00:00
[2024-04-28T01:01:29.121+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_702022', 'manual__2024-04-27T22:35:33.025533+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmpcm9e345x']
[2024-04-28T01:01:29.125+0000] {standard_task_runner.py:91} INFO - Job 247: Subtask load_index_id_702022
[2024-04-28T01:01:29.130+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8415) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-28T01:01:29.132+0000] {standard_task_runner.py:63} INFO - Started process 8416 to run task
[2024-04-28T01:01:29.194+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_702022 manual__2024-04-27T22:35:33.025533+00:00 [running]> on host d933ead87eb5
[2024-04-28T01:01:29.317+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_702022' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T22:35:33.025533+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T22:35:33.025533+00:00'
[2024-04-28T01:01:29.319+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T01:14:19.261+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-04-28T01:14:19.262+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T01:14:19.263+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-04-28T01:14:19.275+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_702022, execution_date=20240427T223533, start_date=20240428T010129, end_date=20240428T011419
[2024-04-28T01:14:19.300+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 247 for task load_index_id_702022 (Task failed due to SystemExit(1); 8416)
[2024-04-28T01:14:19.329+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-28T01:14:19.351+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T01:14:19.357+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
