[2024-04-25T18:04:05.406+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T18:04:05.456+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.task_a manual__2024-04-25T18:02:01.374673+00:00 [queued]>
[2024-04-25T18:04:05.469+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.task_a manual__2024-04-25T18:02:01.374673+00:00 [queued]>
[2024-04-25T18:04:05.471+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 4
[2024-04-25T18:04:05.494+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): task_a> on 2024-04-25 18:02:01.374673+00:00
[2024-04-25T18:04:05.505+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'task_a', 'manual__2024-04-25T18:02:01.374673+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/python_op.py', '--cfg-path', '/tmp/tmp79bc9u_f']
[2024-04-25T18:04:05.509+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask task_a
[2024-04-25T18:04:05.511+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3845) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T18:04:05.513+0000] {standard_task_runner.py:63} INFO - Started process 3846 to run task
[2024-04-25T18:04:05.574+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.task_a manual__2024-04-25T18:02:01.374673+00:00 [running]> on host f9a12f9b65d4
[2024-04-25T18:04:05.694+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T18:02:01.374673+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T18:02:01.374673+00:00'
[2024-04-25T18:04:05.695+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T18:04:05.713+0000] {logging_mixin.py:188} INFO - Process DONE!
[2024-04-25T18:04:05.714+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T18:04:05.715+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-04-25T18:04:05.727+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=my_dag, task_id=task_a, execution_date=20240425T180201, start_date=20240425T180405, end_date=20240425T180405
[2024-04-25T18:04:05.745+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 80 for task task_a (Task failed due to SystemExit(1); 3846)
[2024-04-25T18:04:05.769+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-25T18:04:05.791+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-25T18:04:05.797+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
