[2024-06-11T21:47:19.872+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:47:19.985+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_2979005 manual__2024-06-11T21:47:06.735792+00:00 [queued]>
[2024-06-11T21:47:20.006+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_2979005 manual__2024-06-11T21:47:06.735792+00:00 [queued]>
[2024-06-11T21:47:20.008+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-06-11T21:47:20.051+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_2979005> on 2024-06-11 21:47:06.735792+00:00
[2024-06-11T21:47:20.065+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_2979005', 'manual__2024-06-11T21:47:06.735792+00:00', '--job-id', '299', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmpqjmhpu4t']
[2024-06-11T21:47:20.071+0000] {standard_task_runner.py:91} INFO - Job 299: Subtask load_index_id_2979005
[2024-06-11T21:47:20.072+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=306) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:47:20.073+0000] {standard_task_runner.py:63} INFO - Started process 307 to run task
[2024-06-11T21:47:20.167+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_2979005 manual__2024-06-11T21:47:06.735792+00:00 [running]> on host f7fd8afd804e
[2024-06-11T21:47:20.293+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_2979005' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T21:47:06.735792+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T21:47:06.735792+00:00'
[2024-06-11T21:47:20.295+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:47:34.201+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:47:34.204+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:47:34.206+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:47:34.238+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_2979005, execution_date=20240611T214706, start_date=20240611T214719, end_date=20240611T214734
[2024-06-11T21:47:34.275+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 299 for task load_index_id_2979005 (Task failed due to SystemExit(1); 307)
[2024-06-11T21:47:34.315+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:47:34.357+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:47:34.363+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
