[2024-06-11T21:45:10.821+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:45:10.902+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701228 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:45:10.921+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_701228 scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-06-11T21:45:10.922+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 1
[2024-06-11T21:45:10.957+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_701228> on 2024-06-10 00:00:00+00:00
[2024-06-11T21:45:10.977+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_701228', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmp4_wggtxz']
[2024-06-11T21:45:10.984+0000] {standard_task_runner.py:91} INFO - Job 268: Subtask load_index_id_701228
[2024-06-11T21:45:10.986+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=200) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T21:45:10.989+0000] {standard_task_runner.py:63} INFO - Started process 201 to run task
[2024-06-11T21:45:11.149+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_701228 scheduled__2024-06-10T00:00:00+00:00 [running]> on host f7fd8afd804e
[2024-06-11T21:45:11.419+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_701228' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-10T00:00:00+00:00'
[2024-06-11T21:45:11.421+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:45:11.510+0000] {logging_mixin.py:188} INFO - Ошибка в коде или неверный json
[2024-06-11T21:45:11.512+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:45:11.513+0000] {taskinstance.py:2892} ERROR - Task failed due to SystemExit(1)
[2024-06-11T21:45:11.537+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_mb, task_id=load_index_id_701228, execution_date=20240610T000000, start_date=20240611T214510, end_date=20240611T214511
[2024-06-11T21:45:11.584+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 268 for task load_index_id_701228 (Task failed due to SystemExit(1); 201)
[2024-06-11T21:45:11.611+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:45:11.654+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:45:11.677+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
