[2024-06-11T21:30:35.051+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:30:35.092+0000] {taskinstance.py:2063} INFO - Dependencies not met for <TaskInstance: load_data_mb.load_index_id_701188 scheduled__2024-06-10T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-06-11T21:30:35.108+0000] {local_task_job_runner.py:163} INFO - Task is not able to be run
