[2024-04-28T07:46:10.941+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T07:46:10.983+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_19722414 manual__2024-04-27T22:35:33.025533+00:00 [queued]>
[2024-04-28T07:46:10.996+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_mb.load_index_id_19722414 manual__2024-04-27T22:35:33.025533+00:00 [queued]>
[2024-04-28T07:46:10.998+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T07:46:11.016+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_index_id_19722414> on 2024-04-27 22:35:33.025533+00:00
[2024-04-28T07:46:11.026+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_mb', 'load_index_id_19722414', 'manual__2024-04-27T22:35:33.025533+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/load_data_mb.py', '--cfg-path', '/tmp/tmpl6z340i5']
[2024-04-28T07:46:11.030+0000] {standard_task_runner.py:91} INFO - Job 265: Subtask load_index_id_19722414
[2024-04-28T07:46:11.033+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=17308) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-28T07:46:11.034+0000] {standard_task_runner.py:63} INFO - Started process 17309 to run task
[2024-04-28T07:46:11.099+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_mb.load_index_id_19722414 manual__2024-04-27T22:35:33.025533+00:00 [running]> on host d933ead87eb5
[2024-04-28T07:46:11.207+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_mb' AIRFLOW_CTX_TASK_ID='load_index_id_19722414' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T22:35:33.025533+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T22:35:33.025533+00:00'
[2024-04-28T07:46:11.209+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T07:53:53.438+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2024-04-28T07:53:53.471+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-28T07:53:53.522+0000] {process_utils.py:132} INFO - Sending 15 to group 17309. PIDs of all processes in the group: [17309]
[2024-04-28T07:53:53.524+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 17309
[2024-04-28T07:53:53.545+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-28T07:53:53.625+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T07:53:54.024+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=17309, status='terminated', exitcode=0, started='07:46:10') (17309) terminated with exit code 0
